name: Release Drafter (Changelog)

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    uses: jenkinsci/.github/.github/workflows/release-drafter.yml@master
